### ISSUE TITLE
Issue with orion generate command

### ISSUE THREAD

**Issue by jsdream** [matteodem/orion-cli#13]
For some reason it puts `undefined` into the path `E:\sb-meteor\undefined\private\templates\html\view.html`

`E:\sb-meteor>orion generate view
orion | What's the name of your view? |  test`

`fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);`
                 
`Error: ENOENT, no such file or directory 'E:\sb-meteor\undefined\private\templates\html\view.html'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at C:\Users\Vlad\AppData\Roaming\npm\node_modules\orion-cli\lib\fileManager.js:20:32
    at Array.forEach (native)
    at Object.FileManager.generateTemplates (C:\Users\Vlad\AppData\Roaming\npm\node_modules\orion-cl
i\lib\fileManager.js:19:16)
    at C:\Users\Vlad\AppData\Roaming\npm\node_modules\orion-cli\commands\generate.js:88:29
    at C:\Users\Vlad\AppData\Roaming\npm\node_modules\orion-cli\node_modules\prompt\lib\prompt.js:31
6:32
    at C:\Users\Vlad\AppData\Roaming\npm\node_modules\orion-cli\node_modules\prompt\node_modules\uti
le\node_modules\async\lib\async.js:142:25
    at assembler (C:\Users\Vlad\AppData\Roaming\npm\node_modules\orion-cli\node_modules\prompt\lib\p
rompt.js:313:9)
    at C:\Users\Vlad\AppData\Roaming\npm\node_modules\orion-cli\node_modules\prompt\lib\prompt.js:32
2:32`

**Comment by SlashmanX** [comment]
I fixed this by changing line #2 of fileManager.js to 
`pwd = process.cwd();`

**Comment by matteodem** [comment]
Thanks for providing the fix, I'll fix it when I get to it.

**Comment by jsdream** [comment]
Thanks!

**Comment by osil** [comment]
Hi Matteo, I've had the same issue (it puts 'undefined' into the path) lately on windows 8.1

Thanks in advance!
