### ISSUE TITLE
orion generate model without response

### ISSUE THREAD

**Issue by NeriJunior** [matteodem/orion-cli#14]
When I try to generate models using orion generate model this is the response on terminal:

![captura de tela 2015-04-15 as 01 10 56](https://cloud.githubusercontent.com/assets/17169/7152152/4b2d55e8-e30c-11e4-9ae5-e34e407ce3ca.png)

I'm doing something wrong?

(Mac Os 10.10.2)

**Comment by matteodem** [comment]
It's an interactive shell that should let you enter the name for the "model"

**Comment by NeriJunior** [comment]
![image](https://cloud.githubusercontent.com/assets/17169/7187892/543120cc-e44a-11e4-8088-8a44c6dc85a5.png)

Thanks!
