### ISSUE TITLE
Add coffeescript package if `profile: coffee`

### ISSUE THREAD

**Issue by adamvr** [matteodem/orion-cli#16]

**Comment by matteodem** [comment]
What do you mean?

**Comment by adamvr** [comment]
If you `orion set-profile coffee` you get a bunch of coffeescript files. That's super. Problem is that the coffeescript package doesn't come along with them so they never get compiled and run. It's a little deceptive.

**Comment by matteodem** [comment]
yeah, it's related to #2, I'm really busy right now with finals but I'll get to it asap

**Comment by matteodem** [comment]
Latest version 0.1.7 supports this (see https://github.com/matteodem/orion-cli/commit/3cae3d2c746dbdf6c79b143b96bcbf786369be20)
