### ISSUE TITLE
Requiering sudo for all action within a orion app

### ISSUE THREAD

**Issue by TomSchillemans** [matteodem/orion-cli#22]
I just created a meteor app using orion, but I noticed I needed to run all commands (including orion create) to be sudo. Even creating files and saving them require my password. The last time I tried it it didn't do that. Is it changed to be that way, or did I do something wrong?

**Comment by matteodem** [comment]
What was the problem?

**Comment by TomSchillemans** [comment]
Sorry, I was too quick, turned out the permissions on the `node` and `/usr/local/bin` folders were reset. Had to `chown` it as per http://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo

Sorry, for the concern.

**Comment by matteodem** [comment]
it's fine, was just interested :smile:

**Comment by TomSchillemans** [comment]
Yeah, that is why I closed it right after I got it working.
