### ISSUE TITLE
node not found on ubuntu 14.04

### ISSUE THREAD

**Issue by marfago** [matteodem/orion-cli#3]
After installing orion-cli, the orion command may fail with 
"/usr/bin/env: node: No such file or directory"

A possible workaround is to create a link
ln -s /usr/bin/nodejs /usr/bin/node

**Comment by patvdleer** [comment]
Can confirm, I have/had the same problem although ln -s /usr/bin/nodejs /usr/bin/node didn't fix it for me. I've edited /usr/local/bin/orion env line from node to nodejs which did fix it. I've tried this in a couple of VM's, all 14.04, all of them are affected.

**Comment by gwiant** [comment]
I've had the same issue.  Just installed orion-cli on macbook and same error.

**Comment by fix** [comment]
`sudo apt-get install nodejs-legacy` usually solves this known issue
