### ISSUE TITLE
A lot of issues on app opening in Safari

### ISSUE THREAD

**Issue by dmitrijs-balcers** [matteodem/orion-cli#8]
After making the initial steps as described in guidelines, I receive a lot of errors after opening the app in Safari.

![screen shot 2015-01-08 at 04 54 29](https://cloud.githubusercontent.com/assets/2266310/5657169/8a9db044-96f2-11e4-90a6-33a048a60387.png)

Is it sopposed to be like so?

**Comment by matteodem** [comment]
Isn't actually anything with orion but the boilerplate. I'll have a look

**Comment by dmitrijs-balcers** [comment]
Oh, sorry, my mistake.
Was you able to reproduce the issue?

**Comment by dmitrijs-balcers** [comment]
OK, i did some research, some issues (second to fourth) were caused by safary evernote extension.
Obviously that the behaviour is caused by browser-policy package.

**Comment by matteodem** [comment]
I already pushed a fix for some errors and opened a issue on meteor/meteor for the others.

**Comment by matteodem** [comment]
This should be fixed now.
